name: Create new draft release of technical documentation

# Run this workflow every time a new commit pushed to branch technical-docs
on:
  push:
    branches:
      # master only while developing
      - 'master'
      - 'technical-docs'
    tags-ignore:
      - 'technical-docs-v*'

jobs:
  create-draft-release:
    name: Create draft release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version
        run: "echo ::set-env name=DOCS_VERSION::$(grep VERSION= technical/version.txt | sed -e s/VERSION=//)"

      - name: Debug version
        run: "echo Documentation version: $DOCS_VERSION"

      - name: Tag new release
        run: |
          git tag -a -m "Tagging version ${{ env.DOCS_VERSION }}" technical-docs-v${{ env.DOCS_VERSION }} technical-docs
          git push origin technical-docs-v${{ env.DOCS_VERSION }}

#      - name: Create draft release
#        run: |
#          gh release create
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

