name: Build and test - node-modules-caching

# Run this workflow every time a new commit pushed to any branch except technical-docs
on:
  push:
    paths:
      - "node-modules-caching/**"
      - ".github/workflows/node-modules-caching_build-and-test.yml"

defaults:
  run:
    working-directory: "node-modules-caching"

jobs:
  # This job installs NPM dependencies and caches them as a build artifact
  npm-install-and-cache:
    name: "Install dependencies and cache node_modules"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "node-modules-caching/package-lock.json"

      - name: "Install deps"
        run: npm ci

      - name: "Tar node_modules"
        run: tar cvf node_modules.tar node_modules

      - name: "Compress node_modules tar"
        run: bzip2 -9 node_modules.tar

      - name: "Cache node_modules as Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: node-modules-cache-${{ github.run_id }}
          path: node-modules-caching/node_modules.tar.bz2
          if-no-files-found: error
          retention-days: 1

  # A demo job depending on node_modules
  capitalize1:
    name: capitalize1
    needs: npm-install-and-cache

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "node-modules-caching/package-lock.json"

      - name: "Restore node_modules cache"
        uses: actions/download-artifact@v4
        with:
          name: node-modules-cache-${{ github.run_id }}
          path: node-modules-caching

      - name: "Uncompress node_modules tar"
        run: bunzip2 -v node_modules.tar.bz2

      - name: "Untar node_modules"
        run: tar xvf node_modules.tar

      - name: Run capitalize
        run: npm run capitalize

  # A demo job depending on node_modules
  capitalize2:
    name: capitalize2
    needs: npm-install-and-cache

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "node-modules-caching/package-lock.json"

      - name: "Restore node_modules cache"
        uses: actions/download-artifact@v4
        with:
          name: node-modules-cache-${{ github.run_id }}
          path: node-modules-caching

      - name: "Uncompress node_modules tar"
        run: bunzip2 node_modules.tar.bz2

      - name: "Untar node_modules"
        run: tar xvf node_modules.tar

      - name: Run capitalize
        run: npm run capitalize
