name: Create new draft release of technical documentation

# Run this workflow every time a new commit pushed to branch technical-docs
on:
  push:
    branches:
      # master only while developing
      #- 'master'
      - "technical-docs"
    tags-ignore:
      - "technical-docs-v*"
    paths:
      - "release-docs/**"

defaults:
  run:
    working-directory: "release-docs"

jobs:
  create-draft-release:
    name: Create draft release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine version
        run: "echo DOCS_VERSION=$(grep VERSION= technical/version.txt | sed -e s/VERSION=//) >> $GITHUB_ENV"

      - name: Debug version
        run: "echo ::debug::Documentation version: ${{ env.DOCS_VERSION }}"

      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          zip -j technical-specs-v${{ env.DOCS_VERSION }}.zip technical/api.txt
          gh release create technical-docs-v${{ env.DOCS_VERSION }} technical-specs-v${{ env.DOCS_VERSION }}.zip 'technical/api.txt#API specification' --draft --target technical-docs --title 'Technical documentation release ${{ env.DOCS_VERSION }}' --notes 'TBD: add description of changes'
