name: Create staging PR

# Run this workflow manually
on:
  workflow_dispatch:

env:
  TMP_DIR: '~/tmp'
  ALL_CHANGES_FILE: '~/tmp/all_changes.txt'

defaults:
  run:
    working-directory: 'stage-release-workflow'

jobs:
  create-staging-pr:
    name: Create staging PR

    runs-on: ubuntu-latest

    steps:
      - name: Full checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create temporary directory
        run: |
          mkdir -p ${{ env.TMP_DIR }}

      - name: Checkout staging branch
        run: |
          git checkout staging-branch
          git pull

      - name: List all changes
        run: git log --pretty='%h - %s (%an)' staging-branch..master > ${{ env.ALL_CHANGES_FILE }}

      - name: Create PR to merge master into staging-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base staging-branch --head master --title 'Release candidate' --body-file ${{ env.ALL_CHANGES_FILE }}
